apiVersion: v1
kind: Service
metadata:
  name: authentication
  labels:
    app.kubernetes.io/name: authentication
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: authentication
  ports:
    - name: http
      port: 80
      targetPort: http
