apiVersion: v1
kind: Service
metadata:
  name: payments
  labels:
    app.kubernetes.io/name: payments
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: payments
  ports:
    - name: http
      port: 80
      targetPort: http
