apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app.kubernetes.io/name: notification
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: notification
  ports:
    - name: http
      port: 80
      targetPort: http
