apiVersion: v1
kind: Service
metadata:
  name: notifications
  labels:
    app.kubernetes.io/name: notifications
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: notifications
  ports:
    - name: http
      port: 80
      targetPort: http
