apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
images:
  - name: haikdevacregistry.azurecr.io/user-profile
    newTag: "0.0.2"    
patches:
  - path: patch.yaml