apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-profile            
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/version: "0.0.2"
    spec:
      imagePullSecrets:
        - name: acr-secret       
      containers:
        - name: user-profile    
          env:
            - name: LOG_LEVEL
              value: "debug"