apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    app.kubernetes.io/name: shipping
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: shipping
  ports:
    - name: http
      port: 80
      targetPort: http
