apiVersion: v1
kind: Service
metadata:
  name: user-profile
  labels:
    app.kubernetes.io/name: user-profile
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: user-profile
  ports:
    - name: http
      port: 80
      targetPort: http
