name: Ansible CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'ansible/**'
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ansible

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install ansible

      - name: Add SSH Private Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_PATH }}" > ~/.ssh/ansible_id_rsa
          chmod 600 ~/.ssh/ansible_id_rsa

          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
        shell: bash

      - name: Check Syntax of Playbook
        run: ansible-playbook playbooks/HA_k8s_cluster_init/HA_k8s_cluster_init.yaml --syntax-check

      - name: Check Logical Correctness (Dry Run)
        run: ansible-playbook playbooks/HA_k8s_cluster_init/HA_k8s_cluster_init.yaml --check

      # - name: Run Ansible Playbook
      #   run: ansible-playbook HA_k8s_cluster_init/HA_k8s_cluster_init.yaml